export default {
  extends: ['stylelint-config-standard', 'stylelint-config-recommended-vue'],
  plugins: ['stylelint-order'],
  overrides: [
    { files: ['**/*.vue'], customSyntax: 'postcss-html' },
    { files: ['**/*.scss'], customSyntax: 'postcss-scss' },
  ],
  ignoreFiles: ['**/*.js', '**/*.ts', '**/*.json', '**/*.md', 'node_modules/**/*', 'dist/**/*'],
  rules: {
    'order/properties-order': [
      [
        {
          groupName: 'positioning',
          emptyLineBefore: 'always',
          properties: ['position', 'top', 'right', 'bottom', 'left', 'z-index'],
        },
        {
          groupName: 'display-and-layout',
          emptyLineBefore: 'always',
          properties: [
            'display',
            'flex',
            'flex-grow',
            'flex-shrink',
            'flex-basis',
            'flex-flow',
            'flex-direction',
            'flex-wrap',
            'justify-content',
            'align-items',
            'align-content',
            'align-self',
            'order',
            'grid',
            'grid-template-rows',
            'grid-template-columns',
            'grid-template-areas',
            'grid-auto-rows',
            'grid-auto-columns',
            'grid-auto-flow',
            'grid-column',
            'grid-row',
            'grid-area',
            'gap',
            'row-gap',
            'column-gap',
            'float',
            'clear',
          ],
        },
        {
          groupName: 'box-model',
          emptyLineBefore: 'always',
          properties: [
            'box-sizing',
            'width',
            'min-width',
            'max-width',
            'height',
            'min-height',
            'max-height',
            'margin',
            'margin-top',
            'margin-right',
            'margin-bottom',
            'margin-left',
            'padding',
            'padding-top',
            'padding-right',
            'padding-bottom',
            'padding-left',
          ],
        },
        {
          groupName: 'borders',
          emptyLineBefore: 'always',
          properties: [
            'border',
            'border-width',
            'border-style',
            'border-color',
            'border-top',
            'border-top-width',
            'border-top-style',
            'border-top-color',
            'border-right',
            'border-right-width',
            'border-right-style',
            'border-right-color',
            'border-bottom',
            'border-bottom-width',
            'border-bottom-style',
            'border-bottom-color',
            'border-left',
            'border-left-width',
            'border-left-style',
            'border-left-color',
            'border-radius',
            'border-top-left-radius',
            'border-top-right-radius',
            'border-bottom-right-radius',
            'border-bottom-left-radius',
          ],
        },
        {
          groupName: 'typography',
          emptyLineBefore: 'always',
          properties: [
            'font',
            'font-family',
            'font-size',
            'font-weight',
            'font-style',
            'font-variant',
            'font-size-adjust',
            'font-stretch',
            'font-effect',
            'font-emphasize',
            'line-height',
            'color',
            'text-align',
            'text-align-last',
            'text-decoration',
            'text-emphasis',
            'text-indent',
            'text-justify',
            'text-outline',
            'text-overflow',
            'text-shadow',
            'text-transform',
            'letter-spacing',
            'word-break',
            'word-spacing',
            'word-wrap',
            'white-space',
            'vertical-align',
          ],
        },
        {
          groupName: 'visuals',
          emptyLineBefore: 'always',
          properties: [
            'background',
            'background-color',
            'background-image',
            'background-repeat',
            'background-attachment',
            'background-position',
            'background-position-x',
            'background-position-y',
            'background-clip',
            'background-origin',
            'background-size',
            'box-shadow',
            'outline',
            'outline-width',
            'outline-style',
            'outline-color',
            'outline-offset',
            'opacity',
            'visibility',
            'cursor',
          ],
        },
        {
          groupName: 'animations',
          emptyLineBefore: 'always',
          properties: [
            'transition',
            'transition-delay',
            'transition-duration',
            'transition-property',
            'transition-timing-function',
            'transform',
            'transform-origin',
            'animation',
            'animation-name',
            'animation-duration',
            'animation-fill-mode',
            'animation-play-state',
            'animation-timing-function',
            'animation-delay',
            'animation-iteration-count',
            'animation-direction',
          ],
        },
      ],
      {
        unspecified: 'bottomAlphabetical',
        emptyLineBeforeUnspecified: 'always',
      },
    ],

    'selector-type-no-unknown': [
      true,
      {
        ignoreTypes: ['tag'], // Custom element
      },
    ],

    'selector-class-pattern': null,
    'selector-id-pattern': null,
    'keyframes-name-pattern': null,
    'custom-property-pattern': null,

    'block-no-empty': true,
    'color-hex-length': 'short',
    'declaration-block-no-duplicate-properties': true,
    'no-empty-source': null,
    'no-descending-specificity': null,
    'declaration-property-value-no-unknown': null,
    'font-family-no-missing-generic-family-keyword': null,
    'at-rule-no-unknown': null,
  },
};
