# Garage Configuration File - Production Ready
 
# Core storage paths
metadata_dir = "/var/lib/garage/meta"  # Fast storage preferred
data_dir = "/var/lib/garage/data"      # High capacity storage
 
# Database engine selection
db_engine = "lmdb"  # Fastest option, use "sqlite" for ARM or 32-bit systems
 
# Automatic backup for metadata
metadata_auto_snapshot_interval = "6h"  # Regular snapshots for recovery
 
# Cluster configuration
replication_factor = 1  # Use 3 for production clusters
compression_level = 2   # Balance between CPU usage and storage efficiency
 
# Network configuration
rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"  # Change to actual IP for clustering
rpc_secret = "c83ae7bcec0e93016139f09b3fc6a75453d87b2b5cc39d84735efa939309de39"  # 64-character hex string
 
# S3 API endpoint configuration
[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"


# Static website hosting
[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"
 
# Administrative interface
[admin]
api_bind_addr = "[::]:3903"
admin_token = "secure_admin_token"
metrics_token = "secure_metrics_token"