<template>
  <section>
    <header>
      <div>
        <h3>Two-Factor Authentication (2FA)</h3>
        <p class="section-description">Secure your account by requiring a 6-digit code during login.</p>
      </div>
      <div v-if="userStore.user?.totp_enabled">
        <AppButton type="danger" @click="disable2FA"> Disable 2FA </AppButton>
      </div>

      <div v-else-if="!setupMode">
        <AppButton type="primary" @click="start2FASetup">Enable 2FA</AppButton>
      </div>
    </header>

    <p v-if="userStore.user?.totp_enabled" class="enabled">2FA is currently <strong>enabled</strong> on your account.</p>

    <div v-if="setupMode" class="setup-wizard">
      <p>1. Scan this QR code with your Authenticator application (Google Authenticator, Bitwarden, etc.) :</p>

      <div class="qr-container">
        <QrcodeVue :value="totpData.qr_code_url" :size="200" level="H" />
        <code class="secret-text">Secret Key: {{ totpData.secret }}</code>
      </div>

      <p>2. Enter the verification code generated by your app to finalize activation :</p>
      <input v-model="setupCode" type="text" placeholder="000000" maxlength="6" />

      <div class="footer">
        <AppButton type="secondary" @click="setupMode = false">Cancel</AppButton>
        <AppButton type="primary" @click="confirm2FA">Confirm Activation</AppButton>
      </div>
      <p v-if="setupError" class="error">{{ setupError }}</p>
    </div>
  </section>
</template>

<script setup lang="ts">
import QrcodeVue from 'qrcode.vue';
import Disable2FAModal from '~/components/Security/Disable2FA.vue';

const userStore = useUserStore();

const modals = useModal();

const setupMode = ref(false);
const setupCode = ref('');
const setupError = ref('');
const totpData = ref({ secret: '', qr_code_url: '' });

async function start2FASetup() {
  setupError.value = '';
  try {
    const data = await userStore.request2FA();
    totpData.value = data!;
    setupMode.value = true;
  } catch (err) {
    setupError.value = (err as string) || "Impossible d'initier la configuration 2FA";
  }
}

async function confirm2FA() {
  setupError.value = '';
  try {
    await userStore.confirm2FA(totpData.value.secret, setupCode.value);
    setupMode.value = false;
    setupCode.value = '';
  } catch (err) {
    setupError.value = (err as string) || "Code invalide. L'activation a échoué.";
  }
}

function disable2FA() {
  modals.add(new Modal(shallowRef(Disable2FAModal), { size: 'small' }));
}
</script>

<style scoped lang="scss">
header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.enabled {
  margin: 0;
  font-size: 0.95rem;
  color: var(--text-primary);
  strong {
    color: var(--green);
  }
}
.setup-wizard {
  display: flex;
  flex-direction: column;
  gap: 1.25rem;
  background: var(--surface-overlay);
  border: 1px solid var(--border);
  margin-top: 1rem;
  padding: 1.5rem;
  border-radius: var(--radius-lg);
  p {
    margin: 0;
    font-size: 0.95rem;
  }
}
.qr-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 1rem;
  padding: 1.5rem;
  background: white;
  border-radius: var(--radius-md);
  width: fit-content;
  border: 1px solid var(--border);

  .secret-text {
    font-family: var(--font-mono, monospace);
    font-size: 0.85rem;
    color: #333; /* Lisible sur fond blanc */
    background: var(--surface-background);
    padding: 0.4rem 0.75rem;
    border-radius: var(--radius-sm);
    border: 1px solid var(--border);
    word-break: break-all;
    text-align: center;
  }
}
</style>
