ALTER TABLE users ADD COLUMN totp_secret VARCHAR(255) DEFAULT NULL;
ALTER TABLE users ADD COLUMN totp_enabled BOOLEAN DEFAULT FALSE;

CREATE TABLE user_totp_recovery_codes (
		id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
		code VARCHAR(255) NOT NULL,
		used BOOLEAN DEFAULT FALSE,
    `created_timestamp` BIGINT UNSIGNED NOT NULL,
		FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);