name: Frontend Linters

on:
  pull_request:
    paths:
      - "frontend/**"

jobs:
  lint:
    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "24"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Stylelint (CSS)
        run: npm run lint:css

      - name: Run Typecheck
        run: npm run typecheck
