name: Frontend Linters

on:
  pull_request:
    paths:
      - "frontend/**"

jobs:
  lint:
    if: github.actor != 'dependabot[bot]'

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint

      - name: Run Stylelint (CSS)
        run: bun run lint:css

      - name: Run Typecheck
        run: bun run typecheck
